# Generated by Django 4.2.3 on 2023-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remove_artist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="name",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
