# Generated by Django 4.2.3 on 2023-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_remove_artist_name_artist_band_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="band_name",
            field=models.CharField(default="Solo artist", max_length=255),
        ),
    ]
