# Generated by Django 4.2.3 on 2023-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_artist_band_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
