# Generated by Django 4.2.3 on 2023-07-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_rename_artist_song_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="catalog.genre",
            ),
        ),
    ]
