# Generated by Django 4.2.3 on 2023-07-09 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_song_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="band_name",
            new_name="artist_name",
        ),
    ]
