# Generated by Django 4.2.3 on 2023-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_rename_band_name_artist_artist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="about_genre",
            field=models.TextField(blank=True, null=True),
        ),
    ]
