# Generated by Django 3.2.6 on 2023-07-16 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_auto_20230716_1700"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="length",
            new_name="duration",
        ),
    ]
